
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = [
  # ignore what we're pulling in via bazel
  "k8s.io/kubernetes/pkg/kubectl/cmd*",
  # these are provided by 'rules_go' and can safely be ignored (see https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#dependencies)
  "github.com/google/protobuf*",
  "github.com/golang/protobuf*",
  "github.com/mwitkow/go-proto-validators*",
  "github.com/gogo/protobuf*",
  "golang.org/x/text*",
  "golang.org/x/net*",
  "google.golang.org/grpc*",
  "google.golang.org/genproto*",
]

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.8"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[prune]
  go-tests = true
  unused-packages = true